/* 
 * This file is autogenerated by Grial UIKit build task, please DO NOT modify it
 * manually. Please change colors in the active Theme XAML file and they will be
 * propagated to this file.
 */
using System.Collections.Generic;
using Xamarin.Forms;
using UXDivers.Artina.Shared;

namespace RoboScout.iOS
 {
	internal class ThemeColors : ThemeColorsBase
	{
		private readonly static Dictionary<string, Color> _themeColors = new Dictionary<string, Color>
		{
			{ "AccentColor", Color.FromHex("#FFDA125F") },
			{ "BaseTextColor", Color.FromHex("#D6E1F1") },
			{ "ListViewSelectedItemBackgroundColor", Color.FromHex("#44525ABB") },
			{ "SplashBackgroundColor", Color.FromHex("#525ABB") },
			{ "InverseTextColor", Color.White },
			{ "BrandColor", Color.FromHex("#ad1457") },
			{ "BrandNameColor", Color.FromHex("#FFFFFF") },
			{ "BaseLightTextColor", Color.FromHex("#7b7b7b") },
			{ "OverImageTextColor", Color.FromHex("#FFFFFF") },
			{ "EcommercePromoTextColor", Color.FromHex("#FFFFFF") },
			{ "SocialHeaderTextColor", Color.FromHex("#62527A") },
			{ "ArticleHeaderBackgroundColor", Color.FromHex("#1B1D22") },
			{ "CustomNavBarTextColor", Color.FromHex("#FFFFFF") },
			{ "ListViewItemTextColor", Color.FromHex("#FFFFFF") },
			{ "AboutHeaderBackgroundColor", Color.FromHex("#FFFFFF") },
			{ "BasePageColor", Color.FromHex("#282C37") },
			{ "BaseTabbedPageColor", Color.FromHex("#213D55") },
			{ "MainWrapperBackgroundColor", Color.FromHex("#1B1D22") },
			{ "CategoriesListIconColor", Color.FromHex("#55000000") },
			{ "DashboardIconColor", Color.FromHex("#FFFFFF") },
			{ "ComplementColor", Color.FromHex("#525ABB") },
			{ "TranslucidBlack", Color.FromHex("#44000000") },
			{ "TranslucidWhite", Color.FromHex("#22ffffff") },
			{ "OkColor", Color.FromHex("#22c064") },
			{ "ErrorColor", Color.Red },
			{ "WarningColor", Color.FromHex("#ffc107") },
			{ "NotificationColor", Color.FromHex("#1274d1") },
			{ "SaveButtonColor", Color.FromHex("#22c064") },
			{ "DeleteButtonColor", Color.FromHex("#D50000") },
			{ "LabelButtonColor", Color.FromHex("#ffffff") },
			{ "PlaceholderColor", Color.FromHex("#FFFFFF") },
			{ "PlaceholderColorEntry", Color.FromHex("#505971") },
			{ "RoundedLabelBackgroundColor", Color.FromHex("#525ABB") },
			{ "MainMenuHeaderBackgroundColor", Color.Transparent },
			{ "MainMenuBackgroundColor", Color.FromHex("#1B1F2A") },
			{ "MainMenuSeparatorColor", Color.Transparent },
			{ "MainMenuTextColor", Color.FromHex("#D6E1F1") },
			{ "MainMenuIconColor", Color.FromHex("#D6E1F1") },
			{ "ListViewSeparatorColor", Color.FromHex("#151C22") },
			{ "BaseSeparatorColor", Color.FromHex("#7b7b7b") },
			{ "ChatRightBalloonBackgroundColor", Color.FromHex("#525ABB") },
			{ "ChatBalloonFooterTextColor", Color.FromHex("#FFFFFF") },
			{ "ChatRightTextColor", Color.FromHex("#FFFFFF") },
			{ "ChatLeftTextColor", Color.FromHex("#FFFFFF") }
		};
		public ThemeColors() : base(_themeColors) {}
	}
}
